# localization.yaml
slam_toolbox:
  ros__parameters:
    use_sim_time: True
    mode: localization
    map_file_name: /home/robot/ros2_ws/robot_map.yaml
    map_start_pose: [0.0, 0.0, 0.0]
    use_scan_matching: true
    resolution: 0.05
    transform_timeout: 0.3
    scan_topic: /scan
    scan_queue_size: 1000
    base_frame: base_link
    odom_frame: odom
    map_frame: map
    max_q_size: 1000
