map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: "/home/robot/ros2_ws/robot_map.yaml"

amcl:
  ros__parameters:
    use_sim_time: False
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    scan_topic: "/scan"
    min_particles: 200
    max_particles: 5000
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    update_min_d: 0.2
    update_min_a: 0.2
    resample_interval: 1
    transform_tolerance: 1.0
    recovery_alpha_slow: 0.0
    recovery_alpha_fast: 0.0
planner_server:
  ros__parameters:
    planner_plugin: "nav2_navfn_planner/NavfnPlanner"
    use_sim_time: False

controller_server:
  ros__parameters:
    use_sim_time: False
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      min_x_velocity: 0.1
      max_x_velocity: 0.3
      max_angular_velocity: 1.0
      lookahead_distance: 0.6


bt_navigator:
  ros__parameters:
    default_bt_xml_filename: "behavior_trees/navigate_w_replanning_and_recovery.xml"
    use_sim_time: False

recoveries_server:
  ros__parameters:
    use_sim_time: False
    recovery_behaviors: ["spin", "backup"]
    spin:
      plugin: "nav2_recoveries/Spin"
    backup:
      plugin: "nav2_recoveries/BackUp"

waypoint_follower:
  ros__parameters:
    use_sim_time: False
    plugin: "wait_at_waypoint"

global_costmap:
  global_costmap:
    ros__parameters:
      global_frame: map
      robot_base_frame: base_link
      update_frequency: 2.0
      publish_frequency: 2.0
      resolution: 0.05
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: /scan
          sensor_frame: laser
          marking: true
          clearing: true
          queue_size: 100
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.3
        cost_scaling_factor: 15.0
      always_send_full_costmap: True


local_costmap:
  local_costmap:
    ros__parameters:
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 60
      height: 60
      resolution: 0.05
      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: /scan
          sensor_frame: laser
          marking: true
          clearing: true
          queue_size: 100
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"

