slam_toolbox:
  ros__parameters:
    use_sim_time: false
    mode: mapping
    map_frame: map
    odom_frame: odom
    #base_frame: base_link
    base_frame: base_footprint
    scan_topic: /scan
    publish_scan: true
    publish_map: true
    use_scan_matching: true
    resolution: 0.05
    max_q_size: 1000
